services:
  qloapps:
    image: webkul/qloapps_docker:latest
    ports:
      - "80:80"       # HTTP access
      - "3306:3306"   # MySQL access
      - "2222:22"     # SSH access
    environment:
      USER_PASSWORD: ${USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - qloapps_db:/var/lib/mysql
    restart: unless-stopped

volumes:
  qloapps_db:
